import Head from "next/head";
import Image from "next/image";
import About from "../components/About";
import Articles from "../components/Articles";
import Hero from "../components/Hero";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Easybank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      <Hero />
      <About />
      <Articles />
    </div>
  );
}
